# Use the official Python image from the Docker Hub
FROM python:3.11-slim AS base

# Set environment variables
ENV POETRY_VERSION=1.4.2 \
    POETRY_VIRTUALENVS_CREATE=false \
    PYTHONUNBUFFERED=1

# Install Poetry
RUN pip install "poetry==$POETRY_VERSION"

# Set the working directory
WORKDIR /app

# Copy only the necessary files
COPY pyproject.toml poetry.lock /app/

# Install dependencies
RUN poetry install --no-root --only main

# Copy the rest of the application code
COPY . /app

# Expose the port FastAPI will run on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "biosim_server.api.main:app", "--host", "0.0.0.0", "--port", "8000"]