# Use the official Python image from the Docker Hub
FROM python:3.14-rc-alpine3.21 AS base

# Set environment variables
ENV POETRY_VERSION=1.4.2 \
    POETRY_VIRTUALENVS_CREATE=false \
    PYTHONUNBUFFERED=1 \
    STORAGE_LOCAL_CACHE_DIR="/app/scratch" \
    STORAGE_BUCKET="simdata-bucket" \
    STORAGE_ENDPOINT_URL="http://minio:9000" \
    STORAGE_REGION="us-east-1" \
    STORAGE_GCS_CREDENTIALS_FILE="/app/secret/gcs_credentials.json"


# Install Poetry
RUN pip install "poetry==$POETRY_VERSION"

# Set the working directory
WORKDIR /app

# Copy only the necessary files
COPY pyproject.toml poetry.lock /app/

# Install dependencies
RUN poetry install --no-root --only main

# Copy the rest of the application code
COPY . /app

# Declare the volume for local cache storage
VOLUME ["/app/scratch"]

# Command to run the worker process
CMD ["python", "-m", "biosim_server.worker.worker_main"]