# Api gateway microservice (CURRENTLY STABLE BASE IS LATEST 0.1.5

# FROM ghcr.io/biosimulators/bio-check-base:latest
# FROM ghcr.io/biosimulators/bio-compose-server-base:latest

# TODO: change this back to latest once stable
FROM ghcr.io/biosimulators/bio-compose-server-base:0.0.1-test

SHELL ["/usr/bin/env", "bash", "-c"]

COPY . .

EXPOSE 3001

ENTRYPOINT ["bash", "-c", "poetry run uvicorn main:app --host 0.0.0.0 --port 3001 --reload"]

